apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myhealthypod
  name: myhealthypod
spec:
  containers:
  - image: nginx
    name: myhealthypod
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthypod; sleep 60;
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthypod
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
          - cat
          - /tmp/healthypod
      initialDelaySeconds: 0
      periodSeconds: 5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
