apiVersion: v1
kind: Pod
metadata:
  name: rpof
  labels:
    app: rpof
spec:
  containers:
  - name: busybox-rpof
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'exit 0']
  restartPolicy: OnFailure